### 플레이리스트 그룹 조회
GET http://localhost:8080/api/v1/playlist-groups


### 미로그인 상태로 플레이리스트 조회
GET http://localhost:8080/api/v1/playlists/1

### 로그인 상태로 플레이리스트 조회
GET http://localhost:8080/api/v1/playlists/1
Authorization: Bearer gnirps

### 플레이리스트 좋아요
POST http://localhost:8080/api/v1/playlists/1/likes
Authorization: Bearer gnirps

### 플레이리스트 좋아요 취소
DELETE http://localhost:8080/api/v1/playlists/1/likes
Authorization: Bearer gnirps
